### ISSUE TITLE
Error when using Ruber CL to open a file

### ISSUE THREAD

**Issue by alexbottoni** [stcrocco/ruber#18]
If you try to open a file using the Ruber command line like this:

$ ruber filename.txt

Ruber does not start and you get an error message.

The same happens when you use the context menu command "Open with..." of Linux file manager Caja (based on Nautilus).

My system:
Linux Mint 17 MATE (Gnome 2)
Ruby 1.9.3p484 (2013-11-22 revision 43786) [i686-linux]

**Comment by stcrocco** [comment]
Fixed in commit dd15edab32cea358e96eb8dacccf0eef1948a56c
