### ISSUE TITLE
View Settings are not kept between sessions

### ISSUE THREAD

**Issue by alexbottoni** [stcrocco/ruber#19]
View settings (font size, color/style schema, etc.) are not kept between sessions.

Try this:
1) Open a document
2) Set schema to "solarized dark" (dark background)
3) Exit Ruber
4) Open Ruber again. Open the same document (if not opened automatically). 
You get a default view (white background). View settings are lost.

This happens even if you just close and re-open the document in the same session (that is: without exiting/re-launching Ruber).

My system:
- Linux Mint 17
- Ruby 1.9.3
- Qt (Korundum) 4.13.3
- Ruber 0.0.10

**Comment by stcrocco** [comment]
If I understand correctly, you changed the schema listed in the first line of the dialog (just above the tab bar and left of the New, delete, export and import buttons). This only changes which scheme is displayed (and can be edited) below. To change the scheme to be used by default, you need to select it in the combo box in the last line of the dialog, where it says "Default scheme for Ruber".

I admit it can be a bit confusing (it left me perplexed as well when I opened it to answer your issue). However, this is part of the KDE libraries, not of Ruber itself, so there's nothing I can do about it.

**Comment by alexbottoni** [comment]
Ah, OK. Now I can see how to use it.
