### ISSUE TITLE
View settings are applied on a per-document basis

### ISSUE THREAD

**Issue by alexbottoni** [stcrocco/ruber#20]
View settings (text size, color/style schema) are applied on a per-document basis while they should be applied on a per-session basis (that is: application-wide).

Try this:
1) Open a document
2) Open a second document
3) Set the style/color schema to "solarized dark" (dark blackground) in the second document
4) The schema is applied to the second document only. The first opened document keeps it own default scheme (white background).
4) Open another document (or create a new one)
5) You get a default white background in this last document, as well. Your custom view settings are not applied to newly opened or newly created documents.

That means that you have to apply the view settings by hand to any single document (both old and new ones). I would rather expect to have the same view settings applied to all open documents and to all documents that will be opened/created later in the same session (and even in next sessions, until I make an explicit change to settings).

My system:
- Linux Mint 17
- Ruby 1.9.3
- Qt 4.13.3
- Ruber 0.0.10

**Comment by stcrocco** [comment]
I think the cause of the problem is the same as in issue #18: change the schema at the bottom of the dialog ("Default schema for Ruber") rather than at the top.

**Comment by stcrocco** [comment]
I think the cause of the problem is the same as in issue #19: change the schema at the bottom of the dialog ("Default schema for Ruber") rather than at the top.

**Comment by alexbottoni** [comment]
Yesss.. I think we can consider these two issues closed.
